//
//  File.swift
//  
//
//  Created by Courtney Perreault on 2022-10-24.
//

import Fluent
import Vapor


public final class PromptResponse: Model, Content {
    
    public static let schema = "prompt_responses"
    
    //PK generated by DB
    @ID(key: .id)
    public var id: UUID?
    
    //FK referencing user who responded to prompt
    @Field(key: "user_id")
    public var userId: UUID
    
    //FK referencing prompt being responded to
    @Field(key: "prompt_id")
    public var promptId: UUID
    
    //The textual string representing the response provided by the user
    @Field(key: "response_text")
    public var responseText: String
    
    public init(){
        
    }
    
    public init(id: UUID? = nil, userId: UUID, promptId: UUID, responseText: String){
        self.id = id
        self.userId = userId
        self.promptId = promptId
        self.responseText = responseText
    }
}

