name: SwiftModels

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'Models/**'
      - '!Models/README.md'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'Models/**'
      - '!Models/README.md'

jobs:
  build:
    runs-on: macos-12 #To work with swift versioning (not macos-latest)

    steps:
    - uses: actions/checkout@v2
      with:
          swift-version: "5.5.0"
    - name: Build
      run: |
        cd Models
        swift build -v
    - name: Run tests
      run: |
        cd Models
        swift test -v
